#!/bin/bash
curl -L https://download.jetbrains.com/python/pycharm-community-2022.2.2.tar.gz | tar -xvz
cd pycharm-community-2022.2.2/bin/
./pycharm.sh
sudo echo -e "[Desktop Entry]\nVersion=1.0\nType=Application\nTerminal=false\nIcon=/home$USER/pycharm-community-2022.2.2/bin/pycharm.png\nName[ru_RU]=PyCharm\nExec=/home/$USER/pycharm-community-2022.2.2/bin/pycharm.sh\nName=PyCharm" > /home/$USER/Рабочий\ стол/PyCharm.desktop
sudo chmod ugo+x /home/$USER/Рабочий\ стол/PyCharm.desktop
sudo gtk-update-icon-cache -ft /usr/share/icons/hicolor
